#############################################################################
# Makefile for building: graphics
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ??? 26 16:50:49 2022
# Project:  graphics.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec ../../../share/qt4/mkspecs/unsupported/linux-clang CONFIG+=debug -o Makefile graphics.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -Qunused-arguments -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Qunused-arguments -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../share/qt4/mkspecs/unsupported/linux-clang -I. -I../../../include/qt4/QtCore -I../../../include/qt4/QtGui -I../../../include/qt4 -I. -I.
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		graphics.cpp moc_graphics.cpp
OBJECTS       = main.o \
		graphics.o \
		moc_graphics.o
DIST          = ../../../share/qt4/mkspecs/common/unix.conf \
		../../../share/qt4/mkspecs/common/linux.conf \
		../../../share/qt4/mkspecs/common/gcc-base.conf \
		../../../share/qt4/mkspecs/common/gcc-base-unix.conf \
		../../../share/qt4/mkspecs/common/clang.conf \
		../../../share/qt4/mkspecs/qconfig.pri \
		../../../share/qt4/mkspecs/features/qt_functions.prf \
		../../../share/qt4/mkspecs/features/qt_config.prf \
		../../../share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../share/qt4/mkspecs/features/default_pre.prf \
		../../../share/qt4/mkspecs/features/debug.prf \
		../../../share/qt4/mkspecs/features/default_post.prf \
		../../../share/qt4/mkspecs/features/shared.prf \
		../../../share/qt4/mkspecs/features/warn_on.prf \
		../../../share/qt4/mkspecs/features/qt.prf \
		../../../share/qt4/mkspecs/features/unix/thread.prf \
		../../../share/qt4/mkspecs/features/moc.prf \
		../../../share/qt4/mkspecs/features/resources.prf \
		../../../share/qt4/mkspecs/features/uic.prf \
		../../../share/qt4/mkspecs/features/yacc.prf \
		../../../share/qt4/mkspecs/features/lex.prf \
		../../../share/qt4/mkspecs/features/include_source_dir.prf \
		graphics.pro
QMAKE_TARGET  = graphics
DESTDIR       = 
TARGET        = graphics

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_graphics.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: graphics.pro  ../../../share/qt4/mkspecs/unsupported/linux-clang/qmake.conf ../../../share/qt4/mkspecs/common/unix.conf \
		../../../share/qt4/mkspecs/common/linux.conf \
		../../../share/qt4/mkspecs/common/gcc-base.conf \
		../../../share/qt4/mkspecs/common/gcc-base-unix.conf \
		../../../share/qt4/mkspecs/common/clang.conf \
		../../../share/qt4/mkspecs/qconfig.pri \
		../../../share/qt4/mkspecs/features/qt_functions.prf \
		../../../share/qt4/mkspecs/features/qt_config.prf \
		../../../share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../share/qt4/mkspecs/features/default_pre.prf \
		../../../share/qt4/mkspecs/features/debug.prf \
		../../../share/qt4/mkspecs/features/default_post.prf \
		../../../share/qt4/mkspecs/features/shared.prf \
		../../../share/qt4/mkspecs/features/warn_on.prf \
		../../../share/qt4/mkspecs/features/qt.prf \
		../../../share/qt4/mkspecs/features/unix/thread.prf \
		../../../share/qt4/mkspecs/features/moc.prf \
		../../../share/qt4/mkspecs/features/resources.prf \
		../../../share/qt4/mkspecs/features/uic.prf \
		../../../share/qt4/mkspecs/features/yacc.prf \
		../../../share/qt4/mkspecs/features/lex.prf \
		../../../share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec ../../../share/qt4/mkspecs/unsupported/linux-clang CONFIG+=debug -o Makefile graphics.pro
../../../share/qt4/mkspecs/common/unix.conf:
../../../share/qt4/mkspecs/common/linux.conf:
../../../share/qt4/mkspecs/common/gcc-base.conf:
../../../share/qt4/mkspecs/common/gcc-base-unix.conf:
../../../share/qt4/mkspecs/common/clang.conf:
../../../share/qt4/mkspecs/qconfig.pri:
../../../share/qt4/mkspecs/features/qt_functions.prf:
../../../share/qt4/mkspecs/features/qt_config.prf:
../../../share/qt4/mkspecs/features/exclusive_builds.prf:
../../../share/qt4/mkspecs/features/default_pre.prf:
../../../share/qt4/mkspecs/features/debug.prf:
../../../share/qt4/mkspecs/features/default_post.prf:
../../../share/qt4/mkspecs/features/shared.prf:
../../../share/qt4/mkspecs/features/warn_on.prf:
../../../share/qt4/mkspecs/features/qt.prf:
../../../share/qt4/mkspecs/features/unix/thread.prf:
../../../share/qt4/mkspecs/features/moc.prf:
../../../share/qt4/mkspecs/features/resources.prf:
../../../share/qt4/mkspecs/features/uic.prf:
../../../share/qt4/mkspecs/features/yacc.prf:
../../../share/qt4/mkspecs/features/lex.prf:
../../../share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../share/qt4/mkspecs/unsupported/linux-clang CONFIG+=debug -o Makefile graphics.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/graphics1.0.0 || $(MKDIR) .tmp/graphics1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/graphics1.0.0/ && $(COPY_FILE) --parents graphics.h .tmp/graphics1.0.0/ && $(COPY_FILE) --parents main.cpp graphics.cpp .tmp/graphics1.0.0/ && $(COPY_FILE) --parents graphics.ui .tmp/graphics1.0.0/ && (cd `dirname .tmp/graphics1.0.0` && $(TAR) graphics1.0.0.tar graphics1.0.0 && $(COMPRESS) graphics1.0.0.tar) && $(MOVE) `dirname .tmp/graphics1.0.0`/graphics1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/graphics1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_graphics.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_graphics.cpp
moc_graphics.cpp: graphics.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) graphics.h -o moc_graphics.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_graphics.h
compiler_uic_clean:
	-$(DEL_FILE) ui_graphics.h
ui_graphics.h: graphics.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic graphics.ui -o ui_graphics.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp graphics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

graphics.o: graphics.cpp graphics.h \
		ui_graphics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphics.o graphics.cpp

moc_graphics.o: moc_graphics.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphics.o moc_graphics.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

